
services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - 127.0.0.1:80:80
    networks:
      - AddressAppNetwork
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend
    restart: always
    environment:
      - MONGO_URI=mongodb://database:27017/addressApp
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - AddressAppNetwork
    depends_on:
      - database
  
  database:
    image: mongo:6
    restart: always
    volumes: 
     - database:/data/db
    environment:
      - MONGO_INITDB_DATABASE=addressApp
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - AddressAppNetwork

volumes:
  database:

networks:
  AddressAppNetwork:
    driver: bridge

